### ISSUE TITLE
[Potential Bug] Changeset.ValidateRequired doesn't produce error for required field

### ISSUE THREAD

**Issue by husnimun** [Fs02/grimoire#65]
### Bug Description
ValidateRequired doesn't produce error even though required field is empty

### Steps to reproduce
https://play.golang.org/p/9soJDMn9B8t

### Expected result
`ch.Errors()` should be `[ktp_direksi is required, tdp is required, sk_domisili is required, akta_pendirian is required, akta_perubahan is required]`

### Actual result
`ch.Errors()` is `[]` (empty)

### Possible root cause
- For this to happen, we need to set some fields in the entity. If some fields in the entity has been set to non empty value, ch.zero will be false.
- If the required field is not in the changeset and ch.zero is false, it will check if the required field exists in ch.values
- Required fields exists in ch.values, but it only checks for empty string and nil value.
- Since the required fields (e.g sk_domisili) has fichaURL as its type, it will check for nil value. Since it's not nil, it will continue and skip the loop without adding error to the changeset https://github.com/Fs02/grimoire/blob/master/changeset/validate_required.go#L27

### Possible solution
- Change nil check to zero value check with IsZero https://github.com/Fs02/grimoire/blob/master/changeset/validate_required.go#L27

**Comment by Fs02** [comment]
Hi, Thanks for this very detailed bug.

Yes, you are correct, the problem is indeed in this line (https://github.com/Fs02/grimoire/blob/master/changeset/validate_required.go#L27).

`type fichaURL string` cannot be checked as a normal string because the type is aliased as fichaURL. therefore it skipped the string empty check.

One possible solution I can think of for custom type is maybe to implement an `isZeroer` interface and adds check for type that interface in validate required.

```
type isZeroer interface{
  IsZero() bool
}
```
`isZeroer` should be pretty simple to implement and it's also compatible with other type such as time. https://golang.org/pkg/time/#Time.IsZero

Let me know if you are willing to open pull request for this bug 😄

**Comment by husnimun** [comment]
Thanks for the reply.

Yes, I'm willing to work on this issue. Will add pull request soon :smiley:
